- Makefile
React no longer generates a bundle at build/bundle.js - the name is now
randomized.
> Remove build/bundle.js from `make build`

- package-lock.json
- package.json
This fixes an error I'm getting in dev mode:
```
Uncaught Error: Module build failed: TypeError: chalk.stripColor is not
a function
at stringLength
(/home/nnyby/public_html/econplayground.js/node_modules/react-dev-utils/eslintFormatter.js:70:22)
```
> Downgrade chalk to 1.1.3

- src/Graph.js
- src/utils.js
- src/utils.test.js
There were some assumptions being made about the line slope that caused
incorrect behavior. This should be closer to what we want now.
> Fix line offset / dragging bug - PMT #113433, #113380

- src/GraphMapping.js
- src/utils.js
I'm using DecimalField instead of FloatField in django because this
allows the float values to be precise. I need to constrain the float
values I give it to 2 decimal places in order to be accepted, though.
> Constrain float values to 2 decimal places - PMT #113157

- src/Editor.js
- src/GraphEditor.js
- src/GraphMapping.js
Also: I realized why django-rest-framework may be complaining about null
values that I've already defined a default for -- In the POST request,
the value explicity gets set to `null`, via the giant object in
GraphMapping.js. I've made a change here to not pass in cobb-douglas
config options when it's not necessary, and I'll continue to refine
this.
> Add cobb-douglas axis labels - PMT #113565

- scripts/test.js
`make test` should just run the tests, not go into this annoying
interactive mode.
> Remove default test watch mode

- src/Graph.js
- src/GraphMapping.js
- src/utils.js
Functions don't change value, so const should be fine. I'm still unclear
whether this method, or using traditional function syntax like:
```
function abc() {
}
```
is considered best practice in the es6/react world. My current
understanding is that, both ways are fine and that it doesn't really
matter.
> Use const instead of let for function names

- src/GraphEditor.js
- src/editors/CobbDouglasEditor.js
- src/editors/ConsumptionLeisureEditor.js
- src/editors/ConsumptionSavingEditor.js
- src/editors/NonLinearDemandSupplyEditor.js
- src/form-components/EditableControl.js
- src/form-components/EditableControl.test.js
This will greatly reduce the number of inconsistencies, mistakes, and
time involved to develop these forms.
Still TODO:
* Enable other types of input, like the RangeEditor
* Enable on other graph types
> Introduce EditableControl 

- src/Graph.js
This fixes a bug where if intersection 1's label is defined, but not
the other intersection labels, they all share the first label.
> AD-AS label fix

- src/GraphMapping.js
Using `Infinity` here prevents other graph types from saving.
> Give line 3 a real slope default

- src/GraphEditor.js
The graph's ID isn't always passed in to the GraphEditor, if, for example, we're creating a new graph, via Editor.js.
> remove isRequired from GraphEditor.gId

- src/GraphEditor.js
This commit wraps the graph delete button in a conditional so that it
only appears when editing an existing graph - and does not appear when
creating new graphs.
> Add conditionals to graph delete button

- package-lock.json
- package.json
- src/Graph.js
https://github.com/jsxgraph/jsxgraph/releases/tag/v0.99.7
This required a few changes:
* Lines now response to the `up` event instead of `mouseup`. `mouseup`
wasn't working.
* The curve rendering is now more accurate, which caused performance
issues on some graphs. This is addressed by some adjustments with the
new `recursionDepthLow` and `recursionDepthHigh` options.
> :arrow_up: jsxgraph 0.99.7

- src/GraphEditor.js
- src/GraphViewer.js
This appears whenever the graph data is loading from the REST api, so it
doesn't really make sense to have as currently designed.
> Remove Unknown Graph Type message

- src/GraphEditor.js
- src/editors/CommonGraphEditor.js
- src/editors/CommonGraphSettings.js
This commit:
- Give title to left col "Scenario"
- Order elements in left col:
- Title
- Graph
- Desc: Now uses 4 lines of space by default
- Notes
- In right col, rename "Assignment Type" to "Assignment"
- Rename label "Assignment Type" to "type"
> PMT #115699: Update layout of edit page

- src/buttons/SubmitButton.js
- src/editors/CommonGraphSettings.js
* Remove some unnecessary things from SubmitButton
* Rename "Requires submission" checkbox to "Requires assessment". This
toggles how the Submit button behaves in the student view. Non-assessed
(i.e. non-LTI) graphs can now be submitted, and have feedback displayed
immediately.
> Make some small submission changes

- src/Viewer.js
- src/buttons/SubmitButton.js
The getSubmission call was interfering with the getAssessment call in
this code path. These two requests don't need to happen synchronously in
the promise chain so I've refactored them as necessary.
> bugfix: enable submit button when "requires assessment" is true

- src/Assessment.js
- src/Assessment.test.js
- src/GraphViewer.js
- src/Viewer.js
* Fixed a bug where score can be Infinity because of a divide-by-zero
problem.
* The score in the HTML form that submits to LTI wasn't being updated
dynamically, so I've fixed that as well.
* Add a few more Assessment tests, though the bugs that caused these
problems happened outside of Assessment.js. More holistic tests that
include the behavior in Viewer/GraphViewer are harder to set up, and I
don't have those in place right now.
With these changes, I'm able to see the accurate score come through in
Canvas's gradebook.
> Fix LTI score submission

- src/JXGBoard.js
This reverts commit ceeb5a205a1b68df6f217e5985003f65c3a499f1.
This is causing some problems for Tom, and besides I think there's a
better way to fix this, using the renderer's [screenshot](https://jsxgraph.uni-bayreuth.de/docs/symbols/JXG.SVGRenderer.html#screenshot) functionality.
> Revert "use internal text"

- src/JXGBoard.jsx
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Figure_Role
> Use <figure> element for accessible semantics - ECON-364

- src/utils.js
For some reason, the drf API isn't respecting the
`Accept: application/json` setting here, and returning HTML.
This fixes that problem.
> Always use JSON format for api requests

- package-lock.json
- package.json
- src/GraphEditor.jsx
This commit removes the deprecated React Sticky library and replaces it
with a Bootstrap utility class 'sticky-top'.
> Remove React Sticky

- src/Graph.js
- src/jsxgraphUtils.js
Customize label positions for linear and non-linear Demand/Supply graphs.
> AUC: center label positions

- src/jsxgraphUtils.js
Something broke the centroid calculation here. It looks like it's fixed
by constructing the group of points differently, like this.
> Fix area label centering

- src/JXGBoard.jsx
Fixes a crash on the AUC graph when the slope is moved.
> Don't call removeObject if it doesn't exist

- src/editors/NonLinearDemandSupplyEditor.jsx
- src/form-components/RangeEditor.js
Ideally this max value would be dynamic based on the function choice,
but right now there's a bug messing up the function choice setting for
different graph types, so we have to address that first.
> NLDS graphs: increase max A value - ECON-442

- src/Viewer.jsx
Don't rely on this.state's graphId - this requires the graph data to be imported, and it looks like there is a quirk with synchronizing the promise in getGraph. Just use this.graphId here since this will be immediately present (see where this is set in the constructor).
This fixes a problem where the graphId could potentially be null.
> Load submission off graphId fetched from URL
