ccnmtl/econplayground.js

src/GraphEditor.js

Small changes jthat may be useful when showing Thomas
tomorrow.
Though at the moment I'm actually looking at using jsxgraph instead of
vega, on another branch, since I'm realizing that might be simpler.

Small fix + some updates

---

src/GraphEditor.js
src/GraphPicker.css
src/GraphPicker.js
src/JXGBoard.js
src/graphTypes.js

Now I just need to implement each type.

Connect all graph types to graph editor - PMT #112199

---

src/App.js
src/GraphEditor.js
src/JXGBoard.js
src/graphTypes.js

Authors can now edit line labels and intersection point visibility.

Connect inputs for graph editor form - PMT #112199

---

package-lock.json
package.json

I'm not using `react-scripts start` anymore, so I don't need this.

Remove webpack-dev-server

---

package-lock.json
package.json
public/index.html
src/JXGBoard.js

https://github.com/jsxgraph/jsxgraph/issues/235

Use npm package for jsxgraph

---

src/App.js
src/GraphViewer.js
src/Viewer.js

Also, removing this from App.js.

Add rudimentary graph viewer to Viewer.js

---

src/JXGBoard.js
src/graphTypes.js

These functions should approach 0 but never reach it.

Update function shape for labor market

---

src/App.js
src/GraphEditor.js
src/GraphViewer.js
src/JXGBoard.js
src/Viewer.js

* Graph detail route: Separate viewer from editor
* * Students view the graph, while instructors can edit it.
* Allow slope editing on graph viewer

Graph viewer/editor updates

---

src/graphTypes.js

This addresses some long-standing sources of frustration for me. There
were weird dragging issues related to the placements of points. I've
solved the issue by creating the lines using a different syntax, using
co-ordinates instead of manually created points.

Simplify line drawing

---

src/GraphEditor.js
src/GraphPicker.css
src/GraphViewer.js
src/JXGBoard.js

Graphs need different dimensions on the graph picker and detail pages

Fix graph dimensions

---

src/JXGBoard.js
src/Viewer.js

It wasn't getting loaded correctly via xhr.

Fix wrong graph type bug - PMT #112853

---

src/graphTypes.js

This is a pre-requisite for graph feedback (PMT #112735).
Also, I've generalized the intersection display.

Add snap-to-grid to line dragging behavior

---

src/GraphViewer.js
src/JXGBoard.js
src/Viewer.js
src/graphTypes.js

Add student-entered line movement - first step - PMT #112734

---

src/GraphViewer.js

After talking this through, I've decided for now I'll go with a more
standard quiz format, using canvas for the quiz choices.

Remove submit button

---

src/GraphViewer.js

Actually we do want to post the grade from our tool to Canvas.
This reverts commit dd416a32f5d9a2e58f6375580e75f24158f41fbe.

Revert "Remove submit button" - PMT #112734

---

src/Feedback.js

Connect feedback values to correct messages

---

src/Editor.js
src/Graph.js
src/GraphEditor.js

Also fixes the display intersection checkbox

Add "needs submission" checkbox - PMT #113159

---

src/GraphEditor.js

Add student visibility checkboxes - PMT #112857

---

src/GraphEditor.js
src/GraphViewer.js
src/SlopeEditor.js
src/utils.js

I've also made the handleFormUpdate routine generic, sharing code
between the graph viewer and editor.

Add range input for slope editor - PMT #113193

---

src/Graph.js

This addresses a problem I was seeing where the line couldn't be dragged
to its initial position, and will also fix a submission bug.

Fix PMTs #113345 and #113156

---

package.json

fix(package): update babel-eslint to version 8.1.2

---

package-lock.json
src/GraphViewer.js

(setting the stage for a launch url for the instructor grade view)

Explicit LTI launch url

---

src/GraphViewer.js

We should add some messaging as well, but this at least disables the
submit button when it doesn't do anything.

Disable submit button when `choice` is `null` or 0 - PMT #113515

---

src/GraphEditor.js

This form will completely change soon - this is just a small fix.

Fix id's for cobb-douglas editable labels

---

src/CobbDouglasEditor.js
src/CommonGraphEditor.js
src/GraphEditor.js

I've broken the form out into a few new components:
* CommonGraphEditor: contains form fields common to all graphs - title,
description, etc.
* CobbDouglasEditor: contains cobb-douglas specific fields
This will continue to be refined as I make progress.

GraphEditor refactor

---

src/Graph.js
src/JXGBoard.js

I was kind of wary to do this, thinking I'd have to change a bunch of
values that would mess up some hard-coded graph calculations, but it
turned out to require less changes than I anticipated.

Move X/Y axis labels outside of graph - PMT #113106

---

src/Graph.js
src/GraphMapping.js
src/GraphViewer.js
src/JXGBoard.js
src/Viewer.js

Cobb-Douglas: add shadow curve in student view - PMT #113985

---

package-lock.json
package.json
src/Graph.js

See: https://stackoverflow.com/a/48523839/173630

Allow curve dragging for non-linear demand-supply - PMT #113999

---

src/Graph.js
src/GraphEditor.js
src/NonLinearDemandSupplyEditor.js

I've removed a bunch of code for unused graphs here.

NonLinear demand/supply first steps + cleanup - PMT #113999

---

src/JXGBoard.js

https://jsxgraph.uni-bayreuth.de/docs/symbols/JXG.SVGRenderer.html#layer

Move axis lines to top layer - PMT #114069

---

src/Graph.js
src/GraphEditor.js
src/GraphMapping.js
src/NonLinearDemandSupplyEditor.js

I'm now using a functiongraph for both curves on nonlinear graph - this is
a workaround, see:
https://stackoverflow.com/questions/48773386/jsxgraph-intersection-between-functiongraph-and-line-disappears
This workaround forces me to deal with the curves in a more consistent
way, though. And now positioning is more streamlined for both curves on
this graph. There's now plenty of duplicated code in Graph.js, and can
be refactored, but for now I'm just keeping it in this state without
touching the other graphs too much, since it works.
* Removed unnecessary plotUtils stuff

NonLinear: fix intersection behavior - PMT #113999

---

package.json
src/JXGBoard.js

To prevent unexpected changes.

Pin jsxgraph version and adjust graph labels

---

src/Graph.js

This causes the line to rotate in the middle of the graph instead of at
(0, 0).

Alter slope at x: 2.5 rather than x: 0

---

src/editors/CobbDouglasEditor.js
src/editors/NonLinearDemandSupplyEditor.js

https://stackoverflow.com/questions/48893539/mathjax-how-do-i-remove-the-typesetting-math-100-display-message

Hide mathjax loading messages

---

src/Editor.js
src/Graph.js
src/GraphEditor.js
src/GraphMapping.js
src/GraphViewer.js
src/JXGBoard.js
src/Viewer.js
src/editors/ConsumptionLeisureEditor.js

Converts Consumption-Leisure graph's values to arbitrary numbers.
Depends on: https://github.com/ccnmtl/econplayground/pull/299

Add Consumption-Leisure student view

---

src/Editor.js
src/Graph.js
src/GraphEditor.js
src/GraphViewer.js
src/JXGBoard.js
src/Viewer.js
src/editors/ConsumptionLeisureEditor.js
src/editors/ConsumptionSavingEditor.js

Add Consumption-Saving author functionality

---

src/GraphViewer.js
src/ResetGraphButton.js

Still TODO: Add to the other graph types as well.

Add "Reset Graph" button to consumption-leisure - PMT #113511

---

src/ResetGraphButton.js

Making this button darker, thanks to the note from @sdreher.

"Reset Graph" button style update

---

src/RangeEditor.js
src/editors/CobbDouglasEditor.js

Needs https://github.com/ccnmtl/econplayground/pull/313 to display correctly

Add min-max display to RangeEditor

---

package-lock.json
package.json

I'm not sure how greenkeeper missed this update

:arrow_up: jest 22.4.2

---

package-lock.json
package.json
src/GraphViewer.js
src/form-components/EditableControl.js
src/form-components/EditableControl.test.js

Using react's new TestRenderer - https://reactjs.org/docs/test-renderer.html It looks like this is the way to do it now, rather than with ReactDOM.render.

Add some tests to EditableControl

---

src/Graph.js
src/editors/ConsumptionSavingEditor.js

Consumption-Saving graph updates

---

src/Graph.js

So it's not visible outside of graph area

Fix intersection layer

---

src/Editor.js
src/Viewer.js
src/utils.js

Graph save: Add dynamic error message

---

src/GraphEditor.js
src/editors/ADASEditor.js
src/editors/NonLinearDemandSupplyEditor.js
src/form-components/RangeEditor.js
src/form-components/RangeEditor.test.js
src/utils.js

ADAS graph red line: Add Horizontal option

---

src/Assessment.js
src/Assessment.test.js
src/Graph.js
src/GraphMapping.js
src/GraphViewer.js
src/ResetGraphButton.js

Add more evaluation tests and action types. Right now I'm deriving the
action type from the field name. This should be sufficient for our
current scope - if necessary we can always add this as a new column in
the spreadsheet model.
I'm also beginning to think about how to integrate this with the student
graph viewer.

Assessment system improvements

---

package-lock.json
package.json
src/JXGBoard.js

Looks like componentWillReceiveProps is getting phased out:
https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

Switch from componentWillReceiveProps to componentDidUpdate

---

.travis.yml

Add node 10 to travis.yml

---

src/GraphEditor.js
src/GraphViewer.js
src/editors/DemandSupplyEditor.js

Refactor this template from GraphEditor into a contained file like the
rest of the graph types.

Introduce DemandSupplyEditor

---

src/GraphEditor.js
src/editors/CommonGraphEditor.js
src/editors/NonLinearDemandSupplyEditor.js
src/form-components/RangeEditor.js

This PR is the first step in reorganizing the layout to match the prototype:
* Changes to layout of the Non-Linear Demand Supply graph to use a two column layout
* Updates class names to match the layout of the prototype

Graph edit page layout

---

src/Assessment.js
src/GraphViewer.js
src/Viewer.js
src/buttons/SubmitButton.js

Only displaying feedback in the console at the moment

Connect assessment to labels - PMT #115086

---

src/GraphEditor.js
src/editors/ADASEditor.js
src/editors/CobbDouglasEditor.js
src/editors/CommonGraphEditor.js
src/editors/ConsumptionLeisureEditor.js
src/editors/ConsumptionSavingEditor.js
src/editors/DemandSupplyEditor.js
src/editors/NonLinearDemandSupplyEditor.js

This pull request updates the layout for all of the graph editors to fit within a two column layout.  It tries to stick closely to the markup in the prototype, but deviates occasionally to fit JSX syntax.

Graph Edit Layouts

---

src/Assessment.js
src/Feedback.js
src/GraphViewer.js
src/buttons/SubmitButton.js

Add simple feedback to all graph types

---

src/Viewer.js

woops - i accidentally broke everything

Fix getGraph

---

src/Assessment.js
src/Viewer.js
src/utils.js

Depends on: https://github.com/ccnmtl/econplayground/pull/414

Add assessment loader

---

package-lock.json
package.json

Greenkeeper has been missing this somehow.

:arrow_up: webpack 4.10.2

---

src/GraphViewer.js

Cobb-Douglas values were being used here

Fix axis labels on a few graph types

---

src/Editor.js
src/GraphEditor.js
src/GraphMapping.js
src/Viewer.js
src/editors/CobbDouglasEditor.js

This is now handled in different fields with the new assessment system.

Remove correct/incorrect feedback

---

src/Assessment.js
src/Feedback.js
src/GraphViewer.js

Show feedback for each matching rule.

Assessment: display all feedback - PMT #115584

---

package-lock.json
src/GraphPicker.js

This commit implements templating for the graph picker.
Per the template, the graph itself is supposed to be clickable and there
isn't supposed to be a button to create the graph. I tried few
different CSS techniques but none seemed to work. I left the button for
now.

PMT #115463: Graph picker template

---

src/GraphViewer.js
src/editors/ADASEditor.js
src/editors/CobbDouglasEditor.js
src/editors/ConsumptionLeisureEditor.js
src/editors/ConsumptionSavingEditor.js
src/editors/NonLinearDemandSupplyEditor.js

This commit implements the public view template. It:
- Edits `GraphViewer.js` to match prototype
- Consitantly moves labels and hr's into conditionals (so that labels
don't appear when the condition is false). It makes use of
React.Fragment to wrap elements when needed
- Reformats the editor.js files for new code in conditionals

PMT #115465: Integrate graph view template

---

src/GraphPicker.js

GraphPicker: add href attribute to a tags

---

src/Viewer.js

This fixes a javascript warning.

Add handler for assessment not found

---

src/GraphViewer.js
src/Viewer.js
src/utils.js

https://github.com/ccnmtl/econplayground/pull/450

Remove Submission.choice

---

src/Assessment.js
src/GraphViewer.js
src/Viewer.js
src/buttons/SubmitButton.js
src/utils.js

* Always show submitted graphs in non-submittables, "Submitted" state.
* Show graph submit time to student
* Sum up scores for all fulfilled rules and submit that to Canvas

Graph submission updates

---

src/editors/ConsumptionSavingEditor.js

These are making it display wrong.

Remove parens around Consumption-Saving function

---

src/GraphMapping.js
src/editors/CommonGraphSettings.js

This commit removes the Null val for topics.

PMT #115881: Standardize Topics

---

src/GraphPicker.js

This commit adds an equal amount of spacing around each graph. It also
updates the blurb listed on the page.

PMT #115977: Update layout of Create Graph page

---

src/GraphMapping.js
src/GraphViewer.js

Requires: https://github.com/ccnmtl/econplayground/pull/518

Add feedback to Submission object - PMT #115932

---

package.json

For some reason, greenkeeper isn't updating everything.

:arrow_up: jest 23.5.0

---

src/editors/CobbDouglasEditor.jsx
src/editors/ConsumptionLeisureEditor.jsx
src/editors/ConsumptionSavingEditor.jsx
src/editors/NonLinearDemandSupplyEditor.jsx

https://github.com/mathjax/MathJax/releases/tag/2.7.5

:arrow_up: mathjax 2.7.5

---

src/Editor.js
src/Graph.js
src/GraphEditor.js
src/GraphMapping.js
src/GraphViewer.js
src/JXGBoard.jsx
src/Viewer.js
src/editors/NonLinearDemandSupplyEditor.jsx
src/utils.js

This adds a new function to the NLDS graph: you can now choose the
derivative of the original function via a radio button.

NLDS graph: add function choice - ECON-318

---

src/Graph.js
src/GraphEditor.jsx
src/GraphMapping.js
src/GraphViewer.jsx
src/JXGBoard.jsx
src/Viewer.jsx
src/editors/CobbDouglasEditor.jsx
src/editors/NonLinearDemandSupplyEditor.jsx

This also fixes a bug where the student view wasn't showing the correct
graph when set to the alternative function.

Make NLDS slope labels adjustable - ECON-318

---

src/GraphEditor.jsx

This was only available on the NLDS graph

Add "Student View" button to all graph types

---

package-lock.json
package.json
src/buttons/ExportGraphButton.jsx

I'm still using a custom branch of jsxgraph here, the
dumpToSVG() method hasn't been merged yet -
https://github.com/jsxgraph/jsxgraph/pull/284

Update jsxgraph - ECON-347

---

src/GraphEditor.jsx

Why wasn't using the string syntax here that allows variables, causing
this url to be broken.

Fix "Student View" button

---

src/GraphEditor.jsx

Depends on: https://github.com/ccnmtl/econplayground/pull/899

Add Graph Clone button

---

src/editors/CobbDouglasEditor.jsx
src/editors/ConsumptionLeisureEditor.jsx
src/editors/ConsumptionSavingEditor.jsx
src/editors/NonLinearDemandSupplyEditor.jsx

https://github.com/mathjax/MathJax/releases/tag/2.7.6

:arrow_up: mathjax 2.7.6

---

.travis.yml

This project is using dependabot now.

travis: Remove greenkeeper steps

---

package-lock.json
package.json
src/GraphViewer.jsx
src/utils.js

When CSRF_COOKIE_HTTPONLY is True, the csrf token must be retrieved from the DOM.
https://docs.djangoproject.com/en/3.0/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-or-csrf-cookie-httponly-is-true

Update csrf approach

---

package-lock.json
package.json
src/buttons/ExportGraphButton.jsx

Use jsxgraph's SVG exporter instead of my custom version.
* https://jsxgraph.org/docs/symbols/JXG.SVGRenderer.html
* https://github.com/jsxgraph/jsxgraph/pull/284#issuecomment-617637623

:arrow_up: jsxgraph 1.1.0

---

src/GraphViewer.jsx

This fixes an import error I get when trying to build this project.
See:
https://github.com/commonmark/commonmark.js/issues/136#issuecomment-695774069

Fix commonmark import error

---

src/Graph.js
src/GraphEditor.jsx
src/GraphPicker.jsx
src/utils.js

This PR gets the basic triangle display ready.

Add "area under curve" display basics

---

src/Graph.js

Still TODO: shaded area must be accurate when the intersection point is changed.

Add NLDS curved triangle A - basic sketch

---

src/GraphPicker.jsx

Add "Beta" badge to graph picker - ECON-411

---

package-lock.json
package.json
src/Editor.jsx
src/GraphEditor.jsx
src/GraphPicker.jsx
src/Viewer.jsx
src/editors/CobbDouglasEditor.jsx
src/editors/ConsumptionLeisureEditor.jsx
src/editors/ConsumptionSavingEditor.jsx
src/editors/NonLinearDemandSupplyEditor.jsx

react-mathjax2 was broken with current react version.
Also:
* Use up-to-date react ref syntax
* Downgrade to React 16 (for now. we'll upgrade this separately when we know it works.)

Migrate to mathjax-react

---

src/Graph.js

setPosition() messes up intersect calculations. Put the offset values
directly in the function definition.

Refactor functiongraph line positions

---

src/Graph.js
src/GraphEditor.jsx
src/GraphViewer.jsx
src/JXGBoard.jsx

Turn on and off certain triangles based on the "Surpluses" radio inputs.

AUC: enable triangle configuration

---

src/Graph.js
src/JXGBoard.jsx

We still need to figure out the curve's area calculation here.

Add area display to NLDS AUC graph

---

src/AreaDisplay.jsx
src/Graph.js

Make joint areas a solid color - ECON-422

---

src/Graph.js
src/GraphMapping.js
src/GraphViewer.jsx
src/JXGBoard.jsx
src/Viewer.jsx
src/editors/AreaConfiguration.jsx
src/editors/DemandSupplyEditor.jsx
src/editors/NonLinearDemandSupplyEditor.jsx

Add Shadow Area configuration on student view

---

src/Graph.js
src/GraphEditor.jsx
src/JXGBoard.jsx

* Fix line colors
* Add all NLDS options to GraphEditor

Add some NLDS-Cobb Douglas joint graph updates

---

src/Graph.js
src/jsxgraphUtils.js

* Remove draggability
* Remove polygon borders

Fix AUC area styles

---

src/GraphMapping.js

Graph type 12 needs the L name saved.

Fix labeling bug with vertical joint graph

---

src/Graph.js
src/GraphViewer.jsx

Fix some NLDS joint labeling bugs for Tom.

NLDS joint fixes

---

src/Graph.js
src/JXGBoard.jsx

* Add new y axis label for NLDS graph
* Extend vert intersection line on second graph
* Make the non-linear curve fixed

Vert joint graph fixes

---

src/editors/AreaConfiguration.jsx
src/editors/DemandSupplyEditor.jsx
src/editors/NonLinearDemandSupplyEditor.jsx

Don't show label config on modification assignments

---

src/GraphEditor.jsx
src/GraphViewer.jsx
src/editors/CobbDouglasNLDSEditor.jsx

Clean up label and slider controls for vertical joint graph

---

src/Graph.js
src/GraphEditor.jsx
src/editors/ConsumptionSavingEditor.jsx

Add optimal point labeling

---

src/Graph.js
src/GraphEditor.jsx
src/GraphViewer.jsx
src/editors/ConsumptionSavingEditor.jsx

Optimal Choice: make orange line intercepts configurable

---

package-lock.json
src/GraphPicker.jsx
src/utils.js

This is based on an email sent from Tom.

Re-order and rename graph types

---

src/Editor.jsx
src/GraphEditor.jsx
src/GraphMapping.js
src/GraphViewer.jsx
src/JXGBoard.jsx
src/Viewer.jsx
src/editors/CobbDouglasNLDSEditor.jsx
src/editors/NonLinearDemandSupplyEditor.jsx

Also: Update NLDS axis labels based on feedback

NLDS: allow configurable N name

---

src/GraphEditor.jsx

To reduce code duplication in the DOM templates.

Refactor GraphEditor code

---

src/GraphEditor.jsx
src/GraphViewer.jsx

Basically, use a similar layout on student view as on the instructor
view, when possible. Side-by-side graph types still use the old layout.

Update student view layout for Marc's design

---

src/Graph.js
src/GraphEditor.jsx
src/GraphMapping.js
src/GraphViewer.jsx
src/JXGBoard.jsx
src/editors/ConsumptionLeisureEditor.jsx

This is still in progress, but it's further along so I'd like to get
this merged.

Add Consumption-Leisure optimal choice graph - ECON-408

---

src/Graph.js

Based on Tom's new notes from last week, I realized that a key variable
`c` was mis-defined. The curve now touches the straight line.

Fix optimal choice curve

---

src/Graph.js
src/GraphEditor.jsx
src/GraphViewer.jsx
src/editors/ConsumptionLeisureEditor.jsx

* Add Optimal Point with labels
* Integrate tax rate variable into orange straight line

Add consumption-leisure optimal choice improvements

---

config/webpack.config.dev.js
config/webpack.config.prod.js

The IgnorePlugin used by webpack changed its API slightly
- https://webpack.js.org/plugins/ignore-plugin/

Fix webpack build

---

package-lock.json

Not sure why this was deleted somehow

Add back package-lock.json

---

.github/workflows/build-and-test.yml

Test on current node versions
